### PR TITLE
change iyzipay.rb file name to downcase version

### PR DESCRIPTION
**Pull request by eyupatis**
There is a bug which causes ```uninitialized constant PaymentsController::Iyzipay``` not in Mac Os X but in Linux versions. Because the current version of the filename is ```Iyzipay.rb``` under the ```lib/``` ```Iyzipay``` module not loaded correctly. This pr fixes the issue by changing file name to downcase version.

### CODE REVIEW

**Comment by yyenigun** [comment]
Some travis builds failed. Can you please check and fix the builds?

**Comment by eyupatis** [comment]
Hey @yyenigun, build errors are really interesting. I tried some changes as you see but none of them fixed the issues. How are you trying travis builds on local and not pollute the commit history? I found  [https://github.com/travis-ci/travis-build](url), are you using it locally?

**Comment by yyenigun** [comment]
it is a major change and we need to test all backward compatibility issues. In which version of Ruby and operating system did you get this error? Which locale do you use? It can be a localisation issue.

**Comment by eyupatis** [comment]
OS: Ubuntu 14.04.5 LTS (GNU/Linux 4.8.6-x86_64-linode78 x86_64)
Ruby: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
Locale:

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

I am using macbook pro for local development and did not get this error on my local. When we deploy code to staging environment, we got the above error.

**Comment by brkkyk** [comment]
I have same issue `uninitialized constant` on linux enviroment. It just worked by changing filename Iyzipay.rb to iyzipay.rb in gem lib folder.

**Comment by brkkyk** [comment]
How it can be possible you guys not fixing this problem after 4 months?

**Comment by yyenigun** [comment]
@brkkyk today we will add automated functional tests on our sandbox environment to test backward compatibility on travis. If all tests pass we can merge this pull request this week. Sorry about the delay.

**Comment by yyenigun** [comment]
@brkkyk we implemented functional tests and added travis integration. Can you sync your fork with the upstream repository? If all tests pass we can merge it.

**Comment by brkkyk** [comment]
@yyenigun i create new pull request but travis builds still fails.

**Comment by ktoprakucar** [comment]
@brkkyk we merged issue #21 . there are conflicts on this pull request. please resolve conflicts then push changes. after that, we will review and merge your pull request.

**Pull request closed without merging**
